[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  status = 200!
  conditions = {Role = ["admin"]}

  [[redirects]]
  from = "/dashboard"
  to = "/"
  status = 401!